### ISSUE TITLE
url  /test/aaa/ with  trailing slash match   r.GET("/test/{xxx}"

### ISSUE THREAD

**Issue by tablecell** [zituocn/gow#1]
```
package main

import (
	"github.com/zituocn/gow"
)

func main() {
	r := gow.Default()

	r.GET("/test/{name}", func(c *gow.Context) {
	
	   name := c.Param("name")
		c.JSON(gow.H{
			"code": 0,
			"msg":  name,
		})
	})

	//default :8080
	r.Run()
}

```
curl http://localhost:8080/test/gow/
{
  "id": 0,
  "name": "gow"
}

net/http   return 404 
```
package main
import (
    "fmt"
    "net/http"
)
func main() {
    http.HandleFunc("/test/gow", func (w http.ResponseWriter, r *http.Request) {
        fmt.Fprintf(w, "Welcome to my website!")
    })
   http.ListenAndServe(":8080", nil)
}

```
curl http://localhost:8080/test/gow/
404 page not found

**Comment by zituocn** [comment]
```go
package main
import (
    "fmt"
    "net/http"
)
func main() {
    http.HandleFunc("/test/gow", func (w http.ResponseWriter, r *http.Request) {
        fmt.Fprintf(w, "Welcome to my website!")
    })
   http.ListenAndServe(":8080", nil)
}

```

中使用的 /test/gow，非 /test/gow/  所以会404

gow中已经默认处理 /test/gow/ 和 /test/gow 是相同的地址

**Comment by tablecell** [comment]
@zituocn  zituocn
框架可以这样处理，但是搜索引擎要处理海量的 url/   == url 是一项高成本的工作（比如用url做hash的key来消重）  搜索引擎采取的方式是 url/ 与url是两个网址 ，当然 url/ 可以301/302重定向到 url  （象gin处理的那样） 但这会降低网页权重  效果远不如单个的 url   只是不得已的情况下可以勉强这样处理一下 
最标准的是象net/http 那样  url 算匹配成功  url/  不匹配  这对用搜索引擎是最简单的
而且就从正则匹配的预期来说 /test/正则      这个正则也是不希望匹配结果是象  (xxxx/) 包含最后的斜杠的

**Comment by zituocn** [comment]
感谢你的反馈，我添加一个bool开关，根据自己的业务需要，来确定如何使用。

会在下一个版本中添加。

**Comment by zituocn** [comment]
请查看最新的版本：https://github.com/zituocn/gow/releases/tag/v1.0.8
